fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}

data_file "AUDIO_SYNTHDATA" "audioconfig/mbnzc63eng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/mbnzc63eng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mbnzc63eng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mbnzc63eng"
data_file "AUDIO_GAMEDATA" "audioconfig/mercm177_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mercm177_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mercm177"
data_file "AUDIO_GAMEDATA" "audioconfig/mitstar88_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mitstar88_sounds.dat"
data_file "AUDIO_SYNTHDATA" "audioconfig/mitstar88_amp.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mitstar88"
data_file "AUDIO_SYNTHDATA" "audioconfig/monroec_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/monroec_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/monroec_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_monroec"
data_file "AUDIO_GAMEDATA" "audioconfig/murciev12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/murciev12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_murciev12"
data_file "AUDIO_SYNTHDATA" "audioconfig/mx5nasound_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/mx5nasound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mx5nasound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mx5nasound"
data_file "AUDIO_GAMEDATA" "audioconfig/n4g63t_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/n4g63t_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_n4g63t"
data_file "AUDIO_GAMEDATA" "audioconfig/n55b30t0_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/n55b30t0_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_n55b30t0"
data_file "AUDIO_SYNTHDATA" "audioconfig/nisgtr35_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/nisgtr35_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/nisgtr35_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_nisgtr35"
data_file "AUDIO_GAMEDATA" "audioconfig/nissans20_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/nissans20_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_nissans20"
data_file "AUDIO_GAMEDATA" "audioconfig/npbfs_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/npbfs_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_npbfs"
data_file "AUDIO_GAMEDATA" "audioconfig/npcul_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/npcul_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_npcul"
data_file "AUDIO_GAMEDATA" "audioconfig/npolchar_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/npolchar_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_npolchar"
data_file "AUDIO_GAMEDATA" "audioconfig/nspeedo_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/nspeedo_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_nspeedo"
data_file "AUDIO_GAMEDATA" "audioconfig/p60b40_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/p60b40_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_p60b40"
data_file "AUDIO_GAMEDATA" "audioconfig/perfov10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/perfov10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_perfov10"
data_file "AUDIO_GAMEDATA" "audioconfig/pgt3f6_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/pgt3f6_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_pgt3f6"
data_file "AUDIO_GAMEDATA" "audioconfig/porsche57v10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/porsche57v10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_porsche57v10"
data_file "AUDIO_GAMEDATA" "audioconfig/porschema2_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/porschema2_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_porschema2"
data_file "AUDIO_GAMEDATA" "audioconfig/porschenaflat6_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/porschenaflat6_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_porschenaflat6"
data_file "AUDIO_GAMEDATA" "audioconfig/predatorv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/predatorv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_predatorv8"
data_file "AUDIO_GAMEDATA" "audioconfig/r34sound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/r34sound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_r34sound"