fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}

data_file "AUDIO_SYNTHDATA" "audioconfig/fd3sid_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/fd3sid_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/fd3sid_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_fd3sid"
data_file "AUDIO_SYNTHDATA" "audioconfig/fdvsffeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/fdvsffeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/fdvsffeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_fdvsffeng"
data_file "AUDIO_GAMEDATA" "audioconfig/fer612sc_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/fer612sc_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_fer612sc"
data_file "AUDIO_GAMEDATA" "audioconfig/ferrarif12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ferrarif12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ferrarif12"
data_file "AUDIO_GAMEDATA" "audioconfig/focus2003_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/focus2003_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_focus2003"
data_file "AUDIO_GAMEDATA" "audioconfig/fordvoodoo_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/fordvoodoo_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_fordvoodoo"
data_file "AUDIO_GAMEDATA" "audioconfig/ftypesound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ftypesound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ftypesound"
data_file "AUDIO_GAMEDATA" "audioconfig/gallardov10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/gallardov10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_gallardov10"
data_file "AUDIO_SYNTHDATA" "audioconfig/gresleyh_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/gresleyh_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/gresleyh_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_gresleyh"
data_file "AUDIO_SYNTHDATA" "audioconfig/gt3flat6_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/gt3flat6_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/gt3flat6_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_gt3flat6"
data_file "AUDIO_SYNTHDATA" "audioconfig/gt3rstun_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/gt3rstun_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/gt3rstun_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_gt3rstun"
data_file "AUDIO_GAMEDATA" "audioconfig/hellcatsound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/hellcatsound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_hellcatsound"
data_file "AUDIO_GAMEDATA" "audioconfig/hemisound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/hemisound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_hemisound"
data_file "AUDIO_SYNTHDATA" "audioconfig/italigton_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/italigton_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/italigton_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_italigton"
data_file "AUDIO_GAMEDATA" "audioconfig/jesterv12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/jesterv12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_jesterv12"
data_file "AUDIO_SYNTHDATA" "audioconfig/k20a_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/k20a_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/k20a_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_k20a"
data_file "AUDIO_GAMEDATA" "audioconfig/kawaii_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kawaii_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kawaii"
data_file "AUDIO_GAMEDATA" "audioconfig/kriegerc_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kriegerc_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kriegerc"
data_file "AUDIO_GAMEDATA" "audioconfig/ktm1290r_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ktm1290r_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ktm1290r"
data_file "AUDIO_SYNTHDATA" "audioconfig/lamavgineng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lamavgineng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lamavgineng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lamavgineng"
data_file "AUDIO_GAMEDATA" "audioconfig/lambov10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lambov10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lambov10"
data_file "AUDIO_GAMEDATA" "audioconfig/lfasound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lfasound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lfasound"