fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}

data_file "AUDIO_GAMEDATA" "audioconfig/aq34lot18vhpd_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq34lot18vhpd_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq34lot18vhpd"
data_file "AUDIO_GAMEDATA" "audioconfig/aq35ferf154cd_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq35ferf154cd_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq35ferf154cd"
data_file "AUDIO_GAMEDATA" "audioconfig/aq36hyutheta2n_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq36hyutheta2n_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq36hyutheta2n"
data_file "AUDIO_GAMEDATA" "audioconfig/aq40benw12tt_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq40benw12tt_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq40benw12tt"
data_file "AUDIO_GAMEDATA" "audioconfig/aq45bmws14b23_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq45bmws14b23_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq45bmws14b23"
data_file "AUDIO_GAMEDATA" "audioconfig/aq46forgtebv6_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq46forgtebv6_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq46forgtebv6"
data_file "AUDIO_GAMEDATA" "audioconfig/aq48roln72v12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq48roln72v12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq48roln72v12"
data_file "AUDIO_GAMEDATA" "audioconfig/aqls7raceswap_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aqls7raceswap_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aqls7raceswap"
data_file "AUDIO_GAMEDATA" "audioconfig/aqm275amg_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aqm275amg_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aqm275amg"
data_file "AUDIO_GAMEDATA" "audioconfig/aqtoy2jzstock_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aqtoy2jzstock_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aqtoy2jzstock"
data_file "AUDIO_GAMEDATA" "audioconfig/aston59v12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aston59v12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aston59v12"
data_file "AUDIO_GAMEDATA" "audioconfig/audiea839_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/audiea839_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_audiea839"
data_file "AUDIO_SYNTHDATA" "audioconfig/audr8tteng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/audr8tteng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/audr8tteng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_audr8tteng"
data_file "AUDIO_GAMEDATA" "audioconfig/avesv_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/avesv_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_avesv"
data_file "AUDIO_GAMEDATA" "audioconfig/b58b30_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/b58b30_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_b58b30"
data_file "AUDIO_GAMEDATA" "audioconfig/bmws55_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/bmws55_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_bmws55"
data_file "AUDIO_GAMEDATA" "audioconfig/bnr34ffeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/bnr34ffeng_sounds.dat"
data_file "AUDIO_SYNTHDATA" "audioconfig/bnr34ffeng_amp.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_bnr34ffeng"
data_file "AUDIO_GAMEDATA" "audioconfig/brabus850_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/brabus850_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_brabus850"