fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}

data_file "AUDIO_GAMEDATA" "audioconfig/c6v8sound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/c6v8sound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_c6v8sound"
data_file "AUDIO_SYNTHDATA" "audioconfig/camls3v8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/camls3v8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/camls3v8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_camls3v8"
data_file "AUDIO_GAMEDATA" "audioconfig/castella_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/castella_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_castella"
data_file "AUDIO_GAMEDATA" "audioconfig/chevroletlt4_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/chevroletlt4_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_chevroletlt4"
data_file "AUDIO_GAMEDATA" "audioconfig/cummins5924v_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/cummins5924v_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_cummins5924v"
data_file "AUDIO_GAMEDATA" "audioconfig/cvpiv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/cvpiv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_cvpiv8"
data_file "AUDIO_GAMEDATA" "audioconfig/cypherct_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/cypherct_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_cypherct"
data_file "AUDIO_SYNTHDATA" "audioconfig/czr1eng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/czr1eng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/czr1eng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_czr1eng"
data_file "AUDIO_GAMEDATA" "audioconfig/demonv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/demonv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_demonv8"
data_file "AUDIO_GAMEDATA" "audioconfig/diablov12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/diablov12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_diablov12"
data_file "AUDIO_GAMEDATA" "audioconfig/ea825_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ea825_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ea825"
data_file "AUDIO_GAMEDATA" "audioconfig/ea888_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ea888_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ea888"
data_file "AUDIO_GAMEDATA" "audioconfig/ecoboostv6_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ecoboostv6_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ecoboostv6"
data_file "AUDIO_SYNTHDATA" "audioconfig/ej257_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/ej257_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ej257_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ej257"
data_file "AUDIO_GAMEDATA" "audioconfig/elegyx_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/elegyx_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_elegyx"
data_file "AUDIO_GAMEDATA" "audioconfig/evoixsound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/evoixsound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_evoixsound"
data_file "AUDIO_GAMEDATA" "audioconfig/f10m5_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/f10m5_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_f10m5"
data_file "AUDIO_GAMEDATA" "audioconfig/f20c_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/f20c_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_f20c"
data_file "AUDIO_GAMEDATA" "audioconfig/f40v8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/f40v8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_f40v8"
data_file "AUDIO_GAMEDATA" "audioconfig/f50v12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/f50v12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_f50v12"