fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}


data_file "AUDIO_SYNTHDATA" "audioconfig/lg41ttviperv10_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg41ttviperv10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg41ttviperv10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg41ttviperv10"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg42naviperv10_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg42naviperv10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg42naviperv10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg42naviperv10"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg44nascarv8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg44nascarv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg44nascarv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg44nascarv8"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg48lexlfa_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg48lexlfa_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg48lexlfa_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg48lexlfa"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg50ftypev8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg50ftypev8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg50ftypev8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg50ftypev8"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg51uruscapri_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg51uruscapri_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg51uruscapri_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg51uruscapri"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg52musgt500v8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg52musgt500v8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg52musgt500v8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg52musgt500v8"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg53fer488capri_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg53fer488capri_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg53fer488capri_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg53fer488capri"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg54evoxtun_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg54evoxtun_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg54evoxtun_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg54evoxtun"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg56hons2k_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg56hons2k_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg56hons2k_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg56hons2k"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg57mustangtv8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg57mustangtv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg57mustangtv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg57mustangtv8"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg59hurv10_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg59hurv10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg59hurv10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg59hurv10"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg91timreg_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg91timreg_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg91timreg_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg91timreg"
data_file "AUDIO_SYNTHDATA" "audioconfig/lgcy04murciv12_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lgcy04murciv12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lgcy04murciv12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lgcy04murciv12"
data_file "AUDIO_SYNTHDATA" "audioconfig/lgcyc00qbike700_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lgcyc00qbike700_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lgcyc00qbike700_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lgcyc00qbike700"
data_file "AUDIO_GAMEDATA" "audioconfig/m5cracklemod_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/m5cracklemod_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_m5cracklemod"
data_file "AUDIO_GAMEDATA" "audioconfig/m155slr_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/m155slr_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_m155slr"
data_file "AUDIO_SYNTHDATA" "audioconfig/m158huayra_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/m158huayra_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/m158huayra_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_m158huayra"
data_file "AUDIO_SYNTHDATA" "audioconfig/m297zonda_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/m297zonda_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/m297zonda_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_m297zonda"
data_file "AUDIO_GAMEDATA" "audioconfig/m840t_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/m840t_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_m840t"
data_file "AUDIO_GAMEDATA" "audioconfig/majimalm_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/majimalm_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_majimagt"
data_file "AUDIO_GAMEDATA" "audioconfig/mazrx7fb_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mazrx7fb_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mazrx7fb"