fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}

data_file "AUDIO_GAMEDATA" "audioconfig/sunrise_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/sunrise_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_sunrise"
data_file "AUDIO_GAMEDATA" "audioconfig/supergts_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/supergts_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_supergts"
data_file "AUDIO_GAMEDATA" "audioconfig/suzukigsxr1k_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/suzukigsxr1k_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_suzukigsxr1k"
data_file "AUDIO_GAMEDATA" "audioconfig/svjsound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/svjsound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_svjsound"
data_file "AUDIO_GAMEDATA" "audioconfig/ta4b11_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ta4b11_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ta4b11"
data_file "AUDIO_GAMEDATA" "audioconfig/ta103ninjah2r_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ta103ninjah2r_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ta103ninjah2r"
data_file "AUDIO_GAMEDATA" "audioconfig/ta488f154_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ta488f154_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ta488f154"
data_file "AUDIO_GAMEDATA" "audioconfig/taaud40v8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/taaud40v8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_taaud40v8"
data_file "AUDIO_GAMEDATA" "audioconfig/tampar_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/tampar_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_tampar"
data_file "AUDIO_GAMEDATA" "audioconfig/tascmustanggt50_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/tascmustanggt50_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_tascmustanggt50"
data_file "AUDIO_GAMEDATA" "audioconfig/toysupmk4_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/toysupmk4_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_toysupmk4"
data_file "AUDIO_GAMEDATA" "audioconfig/trumpetzr_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/trumpetzr_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_trumpetzr"
data_file "AUDIO_GAMEDATA" "audioconfig/turismoc_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/turismoc_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_turismoc"
data_file "AUDIO_GAMEDATA" "audioconfig/urusv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/urusv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_urusv8"
data_file "AUDIO_GAMEDATA" "audioconfig/venenov12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/venenov12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_venenov12"
data_file "AUDIO_GAMEDATA" "audioconfig/viperv10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/viperv10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_viperv10"
data_file "AUDIO_SYNTHDATA" "audioconfig/wrxrllyeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/wrxrllyeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/wrxrllyeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_wrxrllyeng"
data_file "AUDIO_SYNTHDATA" "audioconfig/z33dkffeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/z33dkffeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/z33dkffeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_z33dkffeng"
data_file "AUDIO_GAMEDATA" "audioconfig/zr250_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/zr250_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_zr250"