AJShared = AJShared or {}
AJShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
AJShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 100 } } },
	lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 50 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },
	
	oilwell = {
        label = 'Oil Company',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Oilwell Operator', payment = 50 }, 
            ['1'] = { name = 'Oilwell Operator tier 2', payment = 75 }, 
            ['2'] = { name = 'Event Driver tier 2', payment = 100 }, 
            ['3'] = { name = 'Sales', payment = 125 }, 
            ['4'] = { name = 'CEO', isboss = true, payment = 150 }, 
		},
	},
	lspd = {
		label = 'Los Santos Police Department',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Cadet', payment = 75 },
			['2'] = { name = 'Officer', payment = 100 },
			['3'] = { name = 'Senior Officer', payment = 125 },
			['4'] = { name = 'Corporal', payment = 125 },
			['5'] = { name = 'Sergeant', payment = 125 },
			['6'] = { name = 'Lieutenant', payment = 125 },
			['7'] = { name = 'Captain', payment = 125 },
			['8'] = { name = 'Deputy Chief', payment = 125 },
			['9'] = { name = 'Assistant Chief', payment = 125 },
			['10'] = { name = 'Chief', payment = 125 },
			['11'] = { name = 'Commissioner', isboss = true, payment = 150 },
		},
	},
	bcso = {
		label = 'Blaine County Sheriff\'s Office',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadet', payment = 75 },
			['1'] = { name = 'Solo Cadet', payment = 75 },
			['2'] = { name = 'Deputy', payment = 100 },
			['3'] = { name = 'Senior Deputy', payment = 100 },
			['4'] = { name = 'Corporal', payment = 125 },
			['5'] = { name = 'Sergeant', payment = 125 },
			['6'] = { name = 'Lieutenant', payment = 125 },
			['7'] = { name = 'Undersheriff', payment = 125 },
			['8'] = { name = 'Sheriff', isboss = true, payment = 150 },
		},
	},
	sapr = {
		label = 'San Andreas Park Rangers',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadet', payment = 75 },
			['1'] = { name = 'Ranger', payment = 75 },
			['2'] = { name = 'Ranger 1st Class', payment = 100 },
			['3'] = { name = 'Senior Ranger', payment = 100 },
			['4'] = { name = 'Corporal', payment = 125 },
			['5'] = { name = 'Sergeant', payment = 125 },
			['6'] = { name = 'Lieutenant', payment = 125 },
			['7'] = { name = 'Deputy Game Warden', payment = 125 },
			['8'] = { name = 'Game Warden', isboss = true, payment = 150 },
		},
	},
	sahp = {
		label = 'San Andreas Highway Patrols',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadet', payment = 75 },
			['1'] = { name = 'Trooper', payment = 75 },
			['2'] = { name = 'Trooper First Class', payment = 100 },
			['3'] = { name = 'Senior Trooper', payment = 100 },
			['4'] = { name = 'Sergeant', payment = 125 },
			['5'] = { name = 'Assitant Leader', payment = 125 },
			['6'] = { name = 'Leader', isboss = true, payment = 150 },
		},
	},
	doc = {
		label = 'Department Of Correction',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadet', payment = 75 },
			['1'] = { name = 'Solo Cadet', payment = 75 },
			['2'] = { name = 'Officer', payment = 75 },
			['3'] = { name = 'Senior Officer', payment = 75 },
			['4'] = { name = 'Corporal', payment = 125 },
			['5'] = { name = 'Sergeant', payment = 125 },
			['6'] = { name = 'Lieutenant', payment = 125 },
			['7'] = { name = 'Captian', payment = 125 },
			['8'] = { name = 'Deputy Warden', payment = 125 },
			['9'] = { name = 'Warden', isboss = true, payment = 150 },
		},
	},
	sapr = {
		label = 'San Andreas Park Rangers',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadet', payment = 75 },
			['1'] = { name = 'Ranger', payment = 75 },
			['2'] = { name = 'Ranger 1st Class', payment = 100 },
			['3'] = { name = 'Senior Ranger', payment = 100 },
			['4'] = { name = 'Corporal', payment = 125 },
			['5'] = { name = 'Sergeant', payment = 125 },
			['6'] = { name = 'Lieutenant', payment = 125 },
			['7'] = { name = 'Deputy Warden', payment = 125 },
			['8'] = { name = 'Warden', isboss = true, payment = 150 },
		},
	},
	swat = {
		label = 'Special Weapon and tactics',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Officer I', payment = 75 },
			['1'] = { name = 'Officer II', payment = 75 },
			['2'] = { name = 'Officer III', payment = 100 },
			['3'] = { name = 'Officer III+1', payment = 100 },
			['4'] = { name = 'Sergeant I', payment = 125 },
			['5'] = { name = 'Sergeant II', payment = 125 },
			['6'] = { name = 'Captain', payment = 125 },
			['7'] = { name = 'Commander', payment = 125 },
		},
	},
	sasp = {
		label = 'San Andreas State Police ',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'State Officer', payment = 75 },
			['1'] = { name = 'Sergeant', payment = 75 },
			['2'] = { name = 'Senior Sergeant', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 100 },
			['4'] = { name = 'Captain', payment = 125 },
			['5'] = { name = 'Deputy Commissioner', payment = 125 },
			['6'] = { name = 'Commissioner', payment = 125 },
		},
	},
	fib = {
		label = 'Federal Investigation Bureau',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Agent', payment = 100 },
			['1'] = { name = 'Senior Agent', payment = 100 },
			['2'] = { name = 'Supervisory Agent', payment = 125 },
			['3'] = { name = 'Deputy Director', payment = 125 },
			['4'] = { name = 'Director', payment = 125 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Paramedic', payment = 75 },
			['2'] = { name = 'Doctor', payment = 100 },
			['3'] = { name = 'Surgeon', payment = 125 },
			['4'] = { name = 'Chief', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 75 },
			['2'] = { name = 'Event Driver', payment = 100 },
			['3'] = { name = 'Sales', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
}
