fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}

data_file "AUDIO_GAMEDATA" "audioconfig/12vcummins_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/12vcummins_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_12vcummins"
data_file "AUDIO_GAMEDATA" "audioconfig/711pfister_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/711pfister_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_711pfister"
data_file "AUDIO_SYNTHDATA" "audioconfig/918spyeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/918spyeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/918spyeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_918spyeng"
data_file "AUDIO_GAMEDATA" "audioconfig/dlc2015mustsound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/dlc2015mustsound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_2015mustsound"
data_file "AUDIO_SYNTHDATA" "audioconfig/a80ffeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/a80ffeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/a80ffeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_a80ffeng"
data_file "AUDIO_GAMEDATA" "audioconfig/agerasound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/agerasound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_agerasound"
data_file "AUDIO_GAMEDATA" "audioconfig/alfa690t_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/alfa690t_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_alfa690t"
data_file "AUDIO_GAMEDATA" "audioconfig/apollosv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/apollosv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_apollosv8"
data_file "AUDIO_GAMEDATA" "audioconfig/aq02coyotef150_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq02coyotef150_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq02coyotef150"
data_file "AUDIO_GAMEDATA" "audioconfig/aq2jzgterace_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq2jzgterace_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq2jzgterace"
data_file "AUDIO_GAMEDATA" "audioconfig/aq03ej257_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq03ej257_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq03ej257"
data_file "AUDIO_GAMEDATA" "audioconfig/aq05ej257el_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq05ej257el_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq05ej257el"
data_file "AUDIO_GAMEDATA" "audioconfig/aq06nhonc30a_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq06nhonc30a_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq06nhonc30a"
data_file "AUDIO_GAMEDATA" "audioconfig/aq09mazbpze_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq09mazbpze_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq09mazbpze"
data_file "AUDIO_GAMEDATA" "audioconfig/aq10nisvr38dett_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq10nisvr38dett_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq10nisvr38dett"
data_file "AUDIO_GAMEDATA" "audioconfig/aq11bmw298cc_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq11bmw298cc_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq11bmw298cc"
data_file "AUDIO_GAMEDATA" "audioconfig/aq14nisvq37vhrt_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq14nisvq37vhrt_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq14nisvq37vhrt"
data_file "AUDIO_GAMEDATA" "audioconfig/aq21honb16a_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq21honb16a_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq21honb16a"
data_file "AUDIO_GAMEDATA" "audioconfig/aq22honb18c_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq22honb18c_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq22honb18c"
data_file "AUDIO_GAMEDATA" "audioconfig/aq26mit4b11t_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq26mit4b11t_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq26mit4b11t"
data_file "AUDIO_GAMEDATA" "audioconfig/aq29viperv10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq29viperv10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq29viperv10"
data_file "AUDIO_GAMEDATA" "audioconfig/aq31maz13btune_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq31maz13btune_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq31maz13btune"
data_file "AUDIO_GAMEDATA" "audioconfig/aq32hond16z6_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq32hond16z6_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq32hond16z6"