local aaaaa = 'Config/Client'

Config = Config or {}
Config.Secure = {}
Config.Jobs = Config.Jobs or {}
Config.Developing = true

Config.VehicleSounds = {
    ['Pack1'] = {
        ['12vcummins'] = '12vcummins',
        ['711pfister'] = '711pfister',
        ['agerasound'] = 'agerasound',
        ['apollosv8'] = 'apollosv8',
        ['918spyeng'] = '918spyeng',
        ['2015mustsound'] = '2015mustsound',
        ['a80ffeng'] = 'a80ffeng',
        ['apollosv8'] = 'apollosv8',
        ['aq02coyotef150'] = 'aq02coyotef150',
        ['aq2jzgterace'] = 'aq2jzgterace',
        ['aq03ej257'] = 'aq03ej257',
        ['aq05ej257el'] = 'aq05ej257el',
        ['aq06nhonc30a'] = 'aq06nhonc30a',
        ['aq09mazbpze'] = 'aq09mazbpze',
        ['aq10nisvr38dett'] = 'aq10nisvr38dett',
        ['aq11bmw298cc'] = 'aq11bmw298cc',
        ['aq14nisvq37vhrt'] = 'aq14nisvq37vhrt',
        ['aq21honb16a'] = 'aq21honb16a',
        ['aq22honb18c'] = 'aq22honb18c',
        ['aq26mit4b11t'] = 'aq26mit4b11t',
        ['aq29viperv10'] = 'aq29viperv10',
        ['aq31maz13btune'] = 'aq31maz13btune',
        ['aq32hond16z6'] = 'aq32hond16z6',
    },
    ['Pack2'] = {
        ['aq34lot18vhpd'] = 'aq34lot18vhpdt',
        ['aq35ferf154cd'] = 'aq35ferf154cd',
        ['aq36hyutheta2n'] = 'aq36hyutheta2n',
        ['aq40benw12tt'] = 'aq40benw12tt',
        ['aq45bmws14b23'] = 'aq45bmws14b23',
        ['aq46forgtebv6'] = 'aq46forgtebv6',
        ['aq48roln72v12'] = 'aq48roln72v12',
        ['aqls7raceswap'] = 'aqls7raceswap',
        ['aqm275amg'] = 'aqm275amg',
        ['aqtoy2jzstock'] = 'aqtoy2jzstock',
        ['aston59v12'] = 'aston59v12',
        ['audiea839'] = 'audiea839',
        ['audr8tteng'] = 'audr8tteng',
        ['avesv'] = 'avesv',
        ['b58b30'] = 'b58b30',
        ['bmws55'] = 'bmws55',
        ['bnr34ffeng'] = 'bnr34ffeng',
    },
    ['Pack3'] = {
        ['c6v8sound'] = 'c6v8sound',
        ['camls3v8'] = 'camls3v8',
        ['castella'] = 'castella',
        ['chevroletlt4'] = 'chevroletlt4',
        ['cummins5924v'] = 'cummins5924v',
        ['cvpiv8'] = 'cvpiv8',
        ['cypherct'] = 'cypherct',
        ['czr1eng'] = 'czr1eng',
        ['demonv8'] = 'demonv8',
        ['diablov12'] = 'diablov12',
        ['ea825'] = 'ea825',
        ['ea888'] = 'ea888',
        ['ecoboostv6'] = 'ecoboostv6',
        ['ej257'] = 'ej257',
        ['elegyx'] = 'elegyx',
        ['evoixsound'] = 'evoixsound',
        ['f10m5'] = 'f10m5',
        ['f20c'] = 'f20c',
        ['f40v8'] = 'f40v8',
        ['f50v12'] = 'f50v12',
    },
    ['Pack4'] = {
        ['fd3sid'] = 'fd3sid',
        ['fdvsffeng'] = 'fdvsffeng',
        ['fer612sc'] = 'fer612sc',
        ['ferrarif12'] = 'ferrarif12',
        ['focus2003'] = 'focus2003',
        ['fordvoodoo'] = 'fordvoodoo',
        ['ftypesound'] = 'ftypesound',
        ['gallardov10'] = 'gallardov10',
        ['gresleyh'] = 'gresleyh',
        ['gt3flat6'] = 'gt3flat6',
        ['gt3rstun'] = 'gt3rstun',
        ['hellcatsound'] = 'hellcatsound',
        ['hemisound'] = 'hemisound',
        ['italigton'] = 'italigton',
        ['jesterv12'] = 'jesterv12',
        ['k20a'] = 'k20a',
        ['kawaii'] = 'kawaii',
        ['kriegerc'] = 'kriegerc',
        ['ktm1290r'] = 'ktm1290r',
        ['lamavgineng'] = 'lamavgineng',
        ['lambov10'] = 'lambov10',
        ['lfasound'] = 'lfasound',
    },
    ['Pack5'] = {
        ['lg41ttviperv10'] = 'lg41ttviperv10',
        ['lg42naviperv10'] = 'lg42naviperv10',
        ['lg44nascarv8'] = 'lg44nascarv8',
        ['lg48lexlfa'] = 'lg48lexlfa',
        ['lg50ftypev8'] = 'lg50ftypev8',
        ['lg51uruscapri'] = 'lg51uruscapri',
        ['lg52musgt500v8'] = 'lg52musgt500v8',
        ['lg53fer488capri'] = 'lg53fer488capri',
        ['lg54evoxtun'] = 'lg54evoxtun',
        ['lg56hons2k'] = 'lg56hons2k',
        ['lg57mustangtv8'] = 'lg57mustangtv8',
        ['lg59hurv10'] = 'lg59hurv10',
        ['lg91timreg'] = 'lg91timreg',
        ['lgcy04murciv12'] = 'lgcy04murciv12',
        ['lgcyc00qbike700'] = 'lgcyc00qbike700',
        ['m5cracklemod'] = 'm5cracklemod',
        ['m155slr'] = 'm155slr',
        ['m158huayra'] = 'm158huayra',
        ['m840t'] = 'm840t',
        ['majimagt'] = 'majimagt',
        ['m297zonda'] = 'm297zonda',
        ['mazrx7fb'] = 'mazrx7fb',
    },
    ['Pack6'] = {
        ['mbnzc63eng'] = 'mbnzc63eng',
        ['mercm177'] = 'mercm177',
        ['mitstar88'] = 'mitstar88',
        ['monroec'] = 'monroec',
        ['murciev12'] = 'murciev12',
        ['mx5nasound'] = 'mx5nasound',
        ['n4g63t'] = 'n4g63t',
        ['n55b30t0'] = 'n55b30t0',
        ['nisgtr35'] = 'nisgtr35',
        ['nissans20'] = 'nissans20',
        ['npbfs'] = 'npbfs',
        ['npcul'] = 'npcul',
        ['npolchar'] = 'npolchar',
        ['nspeedo'] = 'nspeedo',
        ['p60b40'] = 'p60b40',
        ['perfov10'] = 'perfov10',
        ['pgt3f6'] = 'pgt3f6',
        ['porsche57v10'] = 'porsche57v10',
        ['porschema2'] = 'porschema2',
        ['porschenaflat6'] = 'porschenaflat6',
        ['predatorv8'] = 'predatorv8',
        ['r34sound'] = 'r34sound',
    },
    ['Pack7'] = {
        ['r35sound'] = 'r35sound',
        ['r352sound'] = 'r352sound',
        ['rb26dett'] = 'rb26dett',
        ['rb28dett'] = 'rb28dett',
        ['rb28dett2'] = 'rb28dett2',
        ['elegyrh7'] = 'elegyrh7',
        ['rotary7'] = 'rotary7',
        ['roxanne'] = 'roxanne',
        ['s15sound'] = 's15sound',
        ['s54b32'] = 's54b32',
        ['s63b44'] = 's63b44',
        ['s65b40'] = 's65b40',
        ['s85b50'] = 's85b50',
        ['s1000rr'] = 's1000rr',
        ['sestov10'] = 'sestov10',
        ['shonen'] = 'shonen',
        ['sigma3'] = 'sigma3',
        ['skart'] = 'skart',
        ['sl65amgv12'] = 'sl65amgv12',
        ['subaruej20'] = 'subaruej20',
    },
    ['Pack8'] = {
        ['sunrise'] = 'sunrise',
        ['supergts'] = 'supergts',
        ['suzukigsxr1k'] = 'suzukigsxr1kt',
        ['svjsound'] = 'svjsound',
        ['ta4b11'] = 'ta4b11',
        ['ta103ninjah2r'] = 'ta103ninjah2r',
        ['ta488f154'] = 'ta488f154',
        ['taaud40v8'] = 'taaud40v8',
        ['tampar'] = 'tampar',
        ['toysupmk4'] = 'toysupmk4',
        ['trumpetzr'] = 'trumpetzr',
        ['turismoc'] = 'turismoc',
        ['urusv8'] = 'urusv8',
        ['venenov12'] = 'venenov12',
        ['viperv10'] = 'viperv10',
        ['wrxrllyeng'] = 'wrxrllyeng',
        ['z33dkffeng'] = 'z33dkffeng',
        ['zr250'] = 'zr250',
        ['tascmustanggt50'] = 'tascmustanggt50',
    },
}

Config.DefaultCarSounds = {
    [`trash`] = 'cummins5924v',
}


Config.MetalDetectors = {
    ['Locations'] = {
        vector3(434.23, -981.91, 30.71)
    },
    ['Detect'] = {
        'WEAPON_PISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_HAMMER',
        'WEAPON_BAT',
        'WEAPON_HATCHET',
        'WEAPON_MACHETE',
        'WEAPON_SWITCHBLADE',
        'WEAPON_BATTLEAXE',
        'WEAPON_PISTOL_MK2',
        'WEAPON_COMBATPISTOL',
        'WEAPON_APPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_REVOLVER',
        'WEAPON_SNSPISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_VINTAGEPISTOL',
        'WEAPON_MICROSMG',
        'WEAPON_KNIFE',
        'radio',
        'metalscrap',
    }
}

Config.Jobs= {
    ['Blacklist'] = {
        ['Chicken'] = {
            ['Start'] = vector3(2388.37, 5045.8, 46.37),
            ['Portions'] = {
                vector4(-95.72, 6207.15, 31.03, 311.0),
                vector4(-100.52, 6202.48, 31.03, 222.0),
                vector4(-99.72, 6206.09, 31.03, 226.07),
            },
            ['Packings'] = {
                vector3(-106.44, 6204.29, 31.02),
                vector3(-104.20, 6206.45, 31.02),
                vector3(-101.84, 6208.93, 31.03),
                vector3(-99.91, 6210.9, 31.03),
            },
            ['Sell'] = vector3(-181.03, -1429.19, 31.31),
            --Don't Touch
            ['Chickens'] = {
                vector4(2370.262, 5052.913, 46.437, 276.351),
                vector4(2372.040, 5059.604, 46.444, 223.595),
                vector4(2379.192, 5062.992, 46.444, 195.477),
                vector4(2372.040, 5059.604, 46.444, 223.595),
            },
            ['Portions-chicken'] = {
                vector3(-94.87, 6207.008, 30.08),
                vector3(-100.39, 6201.56, 29.99),
                vector3(-99.90, 6205.48, 30.1),
            },
        }
    },
    ['Whitelist'] = {
        ['Government'] = {
            ['Vehicle'] = vector4(-1313.89, -562.33, 20.8, 215.27),
            ['Vehicles'] = {
                {
                    model = "onebeast",
                    label = "Mayor Car",
                },
                {
                    model = "bmwm5",
                    label = "Security Chief Car",
                },
                {
                    model = "secrsub",
                    label = "Security SUV",
                },
                {
                    model = "gmcyd",
                    label = "Employee SUV",
                },
                {
                    model = "rs7",
                    label = "Secretery Car",
                },
                {
                    model = "745le",
                    label = "Advocate Car",
                },
                {
                    model = "s11mg",
                    label = "Scorpio",
                },
            },
            ['stash'] = vector3(-534.35, -192.17, 47.42),
            ['Private'] = {
                ['Govtash'] = {
                    ["Name"] = 'Employee',
                    ["Coords"] = vector3(-1294.61, -582.07, 34.37),
                    ["text"] = '[E] Government Employee Personal Stash',
                    ["Secret"] = 'Employee_'
                },
                ['Psetash'] = {
                    ["Name"] = {'State Security','Security Chief'},
                    ["Coords"] = vector3(-1285.41, -590.83, 34.37),
                    ["text"] = '[E] Security Head Personal Stash',
                    ["Secret"] = 'Security_'
                },
                ['psmtash'] = {
                    ["Name"] = 'Mayor',
                    ["Coords"] = vector3(-1285.74, -590.83, 41.19),
                    ["text"] = '[E] Mayor Personal Stash',
                    ["Secret"] = 'Mayor_'
                },
                ['psstash'] = {
                    ["Name"] = 'Secretery',
                    ["Coords"] = vector3(-1285.16, -590.76, 37.38),
                    ["text"] = '[E] Secretery Personal Stash',
                    ["Secret"] = 'Secretery_'
                },
                ['ptstash'] = {
                    ["Name"] = 'State Treasure',
                    ["Coords"] = vector3(-1290.27, -585.8, 37.37),
                    ["text"] = '[E] Treasure Personal Stash',
                    ["Secret"] = 'Treasure_'
                },
                ['pstash'] = {
                    ["Name"] = 'State Treasure',
                    ["Coords"] = vector3(-1301.70, -568.60, 41.19),
                    ["text"] = '[E] Governor Personal Stash',
                    ["Secret"] = 'Governor_'
                },
            },
            ['Armory'] = {
                [1] = {
                    ["Name"] = {'Governor', 'Secretery', 'Mayor'},
                    ["Coords"] = vector3(-1306.19, -565.25, 41.19),
                    ["text"] = '[E] Armory',
                    ["Secret"] = 'armory1'
                },
                [2] = {
                    ["Name"] = {'Security Chief', 'Security'},
                    ["Coords"] = vector3(-1301.06, -555.56, 30.57),
                    ["text"] = '[E] Armory',
                    ["Secret"] = 'armory2'
                }
            },
            ['ArmoryItems'] ={
                ['armory1'] = {
                    label = "Governor Armory",
                    slots = 30,
                    items = {
                        [1] = {
                            name = "bandage",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 1,
                        },
                        [2] = {
                            name = "weapon_assaultsmg",
                            price = 0,
                            amount = 50,
                            info = {
                                serie = "",
                            },
                            type = "weapon",
                            slot = 2,
                        },
                        [3] = {
                            name = "ifak",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 3,
                        },
                        [4] = {
                            name = "radio",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 4,
                        },
                        [5] = {
                            name = "bodycam",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 5,
                        },
                        [6] = {
                            name = "weapon_heavypistol",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "weapon",
                            slot = 6,
                        },
                        [7] = {
                            name = "pistol_ammo",
                            price = 20,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 7,
                        },
                        [8] = {
                            name = "smg_ammo",
                            price = 20,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 8,
                        },
                        [9] = {
                            name = "shotgun_ammo",
                            price = 20,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 9,
                        },
                        [10] = {
                            name = "rifle_ammo",
                            price = 20,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 10,
                        },
                        [11] = {
                            name = "weapon_bullpupshotgun",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 11,
                        },
                        [12] = {
                            name = "weapon_mg",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 12,
                        },
                        [13] = {
                            name = "weapon_heavysniper",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 13,
                        },
                        [14] = {
                            name = "weapon_specialcarbine",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 14,
                        },
                        [15] = {
                            name = "heavyarmor",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 15,
                        },
                        [16] = {
                            name = "weapon_stungun",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 16,
                        },
                        [17] = {
                            name = "handcuffs",
                            price = 50,
                            amount = 10,
                            info = {},
                            type = "item",
                            slot = 17,
                        },
                    }
                },
                ['armory2'] = {
                    label = "Security Armory",
                    slots = 30,
                    items = {
                        [1] = {
                            name = "bandage",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 1,
                        },
                        [2] = {
                            name = "weapon_assaultsmg",
                            price = 0,
                            amount = 50,
                            info = {
                                serie = "",
                            },
                            type = "weapon",
                            slot = 2,
                        },
                        [3] = {
                            name = "ifak",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 3,
                        },
                        [4] = {
                            name = "radio",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 4,
                        },
                        [5] = {
                            name = "bodycam",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 5,
                        },
                        [6] = {
                            name = "weapon_heavypistol",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "weapon",
                            slot = 6,
                        },
                        [7] = {
                            name = "pistol_ammo",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 7,
                        },
                        [8] = {
                            name = "smg_ammo",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 8,
                        },
                        [9] = {
                            name = "shotgun_ammo",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 9,
                        },
                        [10] = {
                            name = "rifle_ammo",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 10,
                        },
                        [11] = {
                            name = "weapon_bullpupshotgun",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 11,
                        },
                        [12] = {
                            name = "weapon_specialcarbine",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 12,
                        },
                        [13] = {
                            name = "weapon_stungun",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 13,
                        },
                        [14] = {
                            name = "heavyarmor",
                            price = 0,
                            amount = 50,
                            info = {},
                            type = "item",
                            slot = 14,
                        },
                    }
                }
            }
        },
        ['Doctor'] = {
            ['Surgery'] = vector3(-449.09, -340.53, 34.5)
        }
    }
}