fx_version "cerulean"
games {"gta5"}

files {
	"audioconfig/**.dat",
	"audioconfig/**.rel",
	"audioconfig/**.awc",
	"audioconfig/**.nametable",
	"audioconfig/**.dat10",
	"audioconfig/**.dat151",
	"audioconfig/**.dat54",
  	"sfx/**/*.*"
}

data_file "AUDIO_GAMEDATA" "audioconfig/r35sound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/r35sound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_r35sound"
data_file "AUDIO_GAMEDATA" "audioconfig/dlcr352sound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/dlcr352sound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_r352sound"
data_file "AUDIO_GAMEDATA" "audioconfig/rb26dett_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/rb26dett_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_rb26dett"
data_file "AUDIO_GAMEDATA" "audioconfig/rb28dett_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/rb28dett_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_rb28dett"
data_file "AUDIO_GAMEDATA" "audioconfig/rb28dett2_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/rb28dett2_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_rb28dett2"
data_file "AUDIO_GAMEDATA" "audioconfig/dodgehemihellcat_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/dodgehemihellcat_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_redeye"
data_file "AUDIO_GAMEDATA" "audioconfig/elegyrh7_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/elegyrh7_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_rh7elegy"
data_file "AUDIO_GAMEDATA" "audioconfig/rotary7_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/rotary7_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_rotary7"
data_file "AUDIO_GAMEDATA" "audioconfig/roxanne_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/roxanne_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_roxanne"
data_file "AUDIO_GAMEDATA" "audioconfig/s15sound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s15sound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s15sound"
data_file "AUDIO_GAMEDATA" "audioconfig/s54b32_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s54b32_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s54b32"
data_file "AUDIO_GAMEDATA" "audioconfig/s63b44_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s63b44_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s63b44"
data_file "AUDIO_GAMEDATA" "audioconfig/s65b40_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s65b40_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s65b40"
data_file "AUDIO_GAMEDATA" "audioconfig/s85b50_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s85b50_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s85b50"
data_file "AUDIO_GAMEDATA" "audioconfig/s1000rr_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s1000rr_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s1000rr"
data_file "AUDIO_GAMEDATA" "audioconfig/sestov10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/sestov10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_sestov10"
data_file "AUDIO_GAMEDATA" "audioconfig/shonen_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/shonen_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_shonen"
data_file "AUDIO_GAMEDATA" "audioconfig/sigma3_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/sigma3_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_sigma3"
data_file "AUDIO_GAMEDATA" "audioconfig/skart_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/skart_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_skart"
data_file "AUDIO_GAMEDATA" "audioconfig/sl65amgv12_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/sl65amgv12_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_sl65amgv12"
data_file "AUDIO_GAMEDATA" "audioconfig/subaruej20_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/subaruej20_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_subaruej20"